import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { DatabaseSchemaDefinition } from "@melon/db";

export interface PrismaCodegenOptions {
	outputPath: string;
	emitHooks?: boolean;
	clientModuleName?: string;
}

/**
 * Generates TypeScript client files from a Melon schema definition.
 */
export async function generateClient(
	schema: DatabaseSchemaDefinition,
	options: PrismaCodegenOptions,
): Promise<void> {
	const outputPath = options.outputPath;
	await mkdir(outputPath, { recursive: true });

	const modelNames = Object.keys(schema.collections);
	const typeLines = modelNames
		.map((collection) => {
			const meta = schema.collections[collection];
			if (!meta) return "";
			const fieldLines = Object.entries(meta.fields)
				.map(([name, field]) => {
					const tsType = melonScalarToTs(field.kind);
					return `  ${name}${field.nullable ? "?" : ""}: ${tsType};`;
				})
				.join("\n");
			return `export interface ${toPascalCase(collection.slice(0, -1))} {\n${fieldLines}\n}`;
		})
		.filter(Boolean)
		.join("\n\n");

	const schemaJson = JSON.stringify(schema, null, 2);
	const clientName = options.clientModuleName ?? "MelonClient";

	await writeFile(
		join(outputPath, "types.ts"),
		`// Generated by melon-prisma — do not edit manually\n\n${typeLines}\n`,
	);

	await writeFile(
		join(outputPath, "schema.ts"),
		`// Generated by melon-prisma — do not edit manually
import { createMelonSchema, type DatabaseSchemaDefinition } from "@melon/db";

const definition: DatabaseSchemaDefinition = ${schemaJson};

export const schema = createMelonSchema(definition);
export { definition };
`,
	);

	await writeFile(
		join(outputPath, "client.ts"),
		`// Generated by melon-prisma — do not edit manually
import type { MelonDatabase } from "@melon/db";
import { createPrismaLikeClient, type PrismaLikeClient } from "@melon/db-prisma";

export type ${clientName} = PrismaLikeClient;

export function create${clientName}(db: MelonDatabase): ${clientName} {
  return createPrismaLikeClient(db);
}
`,
	);

	const hookExports = options.emitHooks
		? `\nexport * from "./hooks.ts";\n`
		: "";

	if (options.emitHooks) {
		const hookLines = modelNames
			.map((collection) => {
				const hookName = `use${toPascalCase(collection)}FindMany`;
				return `export { useFindMany as ${hookName} } from "@melon/db-react";`;
			})
			.join("\n");
		await writeFile(
			join(outputPath, "hooks.ts"),
			`// Generated by melon-prisma — do not edit manually\n${hookLines}\n`,
		);
	}

	await writeFile(
		join(outputPath, "index.ts"),
		`// Generated by melon-prisma — do not edit manually
export * from "./types.ts";
export * from "./schema.ts";
export * from "./client.ts";${hookExports}`,
	);
}

function melonScalarToTs(kind: string): string {
	switch (kind) {
		case "number":
			return "number";
		case "boolean":
			return "boolean";
		case "date":
			return "Date";
		case "json":
			return "Record<string, unknown>";
		case "bytes":
			return "Uint8Array";
		default:
			return "string";
	}
}

function toPascalCase(value: string): string {
	return value.charAt(0).toUpperCase() + value.slice(1);
}
